prometheus:
  image: prom/prometheus
  ports:
   - "9090:9090"
grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  links:
   - prometheus
pushgateway:
  image: prom/pushgateway
  ports:
   - "9091:9091"
  links:
   - prometheus