global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 5s
    scrape_timeout: 10s
    target_groups:
      - targets: ['pushgateway:9091']